version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: thomas1010
      MYSQL_ROOT_PASSWORD: thomas1010
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306